apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-something
  name: frontend-something
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-something
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-something
    spec:
      nodeName: node2
      containers:
      - image: nvrbckdown/something
        name: something
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources: {}
status: {}
