apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: a3b24509d91bca04330a9ad758b6b2c70dfceae89c827356bdf2c7de6263c6eb
    cni.projectcalico.org/podIP: 10.233.68.93/32
    cni.projectcalico.org/podIPs: 10.233.68.93/32
  creationTimestamp: "2024-02-12T14:12:25Z"
  labels:
    author: azizbek
    last: final
  name: nginx2
  namespace: azizbek
  resourceVersion: "4960016"
  uid: 8784a8bc-f4fd-47fa-9d68-17c2e1b33e35
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx2
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cv8b7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node4
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-cv8b7
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://5534cb28a30213e06edaaac611899a121631a36d39ff66d0c501e82cc6819c15
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:5f44022eab9198d75939d9eaa5341bc077eca16fa51d4ef32d33f1bd4c8cbe7d
    lastState: {}
    name: nginx2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-12T14:12:27Z"
  hostIP: 95.216.206.151
  phase: Running
  podIP: 10.233.68.93
  podIPs:
  - ip: 10.233.68.93
  qosClass: BestEffort
  startTime: "2024-02-12T14:12:25Z"
