apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 620cc0757b197005ccabaf5019473979259e86561e521392517c751d654af104
    cni.projectcalico.org/podIP: 10.233.66.89/32
    cni.projectcalico.org/podIPs: 10.233.66.89/32
  creationTimestamp: "2024-02-12T14:12:05Z"
  labels:
    author: azizbek
    last: final
  name: nginx1
  namespace: azizbek
  resourceVersion: "4959984"
  uid: 49a97781-9222-4d0e-9c34-97d3e0acfcb3
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vwzd4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vwzd4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:06Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:06Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-12T14:12:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://75223a8914271f6053d75f669bd70cc74a74d3c1ce558c03d19a622430af9242
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:5f44022eab9198d75939d9eaa5341bc077eca16fa51d4ef32d33f1bd4c8cbe7d
    lastState: {}
    name: nginx1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-12T14:12:06Z"
  hostIP: 65.109.14.160
  phase: Running
  podIP: 10.233.66.89
  podIPs:
  - ip: 10.233.66.89
  qosClass: BestEffort
  startTime: "2024-02-12T14:12:05Z"
