apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: node-printer
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: node-printer
    spec:
      parallelism: 5
      completions: 10
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx
            name: node-printer
            command:
            - /bin/sh
            - -c
            - echo $NODE
            env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
status: {}
